# Generated by Django 3.0.6 on 2020-05-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='sensors',
            field=models.ManyToManyField(to='manager.Sensor'),
        ),
        migrations.AddField(
            model_name='plant',
            name='tasks',
            field=models.ManyToManyField(to='manager.Task'),
        ),
    ]
