# Generated by Django 3.0.6 on 2020-05-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20200512_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='command',
            field=models.CharField(default='NOOP', max_length=100),
            preserve_default=False,
        ),
    ]
